### ISSUE TITLE
README and Source code are inconsistent

### ISSUE THREAD

**Issue by Annlean** [QuMuLab/dsharp#19]
Hi, 

I followed the README to build model, the USAGE said "To use the version with GMP, copy the Makefile_gmp to Makefile. Otherwise, copy Makefile_nogmp to Makefile and proceed normally." 

but Makefile is not in source code and I'm sure I have the GMP library (libgmp-dev).

what should I do to build Dsharp?

**Comment by VincentDerk** [comment]
It means you should rename either one of the Makefiles into `Makefile` such that when you run the `make` command, it will use that file.

**Comment by haz** [comment]
@VincentDerk is spot on. Let us know if doing that doesn't work for you.
